project:
  type: book
  output-dir: _book
  
  preview: 
    port: 3333
    browser: true
    watch-inputs: true
    navigate: true

book:
  title: "Version Control of Code and Data for Scientists"
  search: true
  repo-url: https://github.com/lnnrtwttkhn/version-control-book/
  repo-branch: main
  repo-actions: [issue, source]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  favicon: static/git-icon.svg
  twitter-card: false
  site-url: https://lennartwittkuhn.com/version-control-book
#  date: "6/3/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  page-navigation: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    # fontcolor: black
    # linkcolor: black
    link-external-newwindow: true
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    number-sections: false
    anchor-sections: true
    # layout (https://quarto.org/docs/reference/formats/html.html#layout):
    fig-cap-location: margin
    page-layout: full
    title-block-style: none
    # code (https://quarto.org/docs/reference/formats/html.html#code):
    code-fold: false
    code-overflow: wrap
    code-line-numbers: false
    code-copy: true
    code-link: false
    code-annotations: hover
    code-tools: false
    highlight-style: monokai
    # references:
    bibliography: references.bib
    citations-hover: true
    citation-location: document
    citeproc: true
    # footnotes:
    footnotes-hover: true
    include-after-body: plausible.html

metadata-files:
  - _authors.yml
  - _affiliations.yml
